package exceptionHandling;

public class TryCatchFinallyCase2 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		//Exception occurs - catch block did not handled - finally execute		
		/*try{
			int data=25/0;
			System.out.println(data);
			}
			catch(ArithmeticException e){
				System.out.println(e);
				}
			finally{
				System.out.println("finally block is always executed");
				}
			System.out.println("rest of the code...");*/

	}

}
